In [18]:
import pandas as pd

df = pd.read_csv('/home/lmin/Desktop/test/crawlers/data/Prime_movie1970_1954.csv')#匯入資料
df = pd.read_csv('/home/lmin/Desktop/test/crawlers/data/Prime_movie1989_1947.csv')
df = pd.read_csv('/home/lmin/Desktop/test/crawlers/data/Prime_movie2020_1990.csv')
df.fillna('NaN')#將空值欄位填入NaN
ndf = df.drop(['style'], axis=1)#刪除style,裡面太多無用訊息
ndf.sort_values(by='rating_avg', ascending=False)#評分由高至低排序

,rating_total,rating_avg,finalist,movie_description,cast,language,country,company,film_location
234,27,9.7,The Line (2019) - IMDb,"\n Pedro and Rosa, two mini...","Simone Kliass\n, Rodrigo Santoro\n",English,English,Arvore Immersive Experiences,NaN
1490,"1,413,022",9.5,Breaking Bad (TV Series 2008–2013) - IMDb,\n A high school chemistry ...,"Bryan Cranston\n, Anna Gunn\n, Aaron Paul\n, ...",USA,USA,High Bridge Productions,"906 Park Avenue SW, Albuquerque, New Mexico, USA"
461,"93,293",9.5,Planet Earth II (TV Mini-Series 2016) - IMDb,\n David Attenborough retur...,David Attenborough\n,UK,UK,BBC Natural History Unit (NHU),NaN
223,"3,784",9.4,Seven Worlds One Planet (TV Mini-Series 2019) ...,\n Millions of years ago in...,"David Attenborough\n, Peter Drost\n",UK,UK,BBC Studios,NaN
1469,"164,369",9.4,Planet Earth (TV Mini-Series 2006) - IMDb,"\n Emmy Award-winning, 11 e...","David Attenborough\n, Sigourney Weaver\n, Tho...",UK,UK,British Broadcasting Corporation (BBC),NaN
...,...,...,...,...,...,...,...,...,...
2575,NaN,NaN,Sunday Best (TV Series 1991– ) - IMDb,\n,Carl Reiner\n,English,English,IMDbPro,NaN
2613,NaN,NaN,Perlman in Russia (1992) - IMDb,\n,Itzhak Perlman\n,IMDbPro,NaN,IMDbPro,NaN
2623,NaN,NaN,Pavarotti on Miami Beach (1996) - IMDb,\n,"Rich Capparela\n, Cynthia Lawrence\n, Leone M...",English,English,IMDbPro,NaN
2636,NaN,NaN,Barbara Mandrell: Steppin Out (1996) - IMDb,\n,Barbara Mandrell\n,English,English,IMDbPro,NaN
2660,NaN,NaN,Magicians' Favorite Magicians (1996) - IMDb,\n,"Harry Anderson\n, Jonathan Pendragon\n",English,English,IMDbPro,NaN

In [17]:
df.to_csv('New_primovie.csv', encoding='utf-8')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2677 entries, 0 to 2676
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating_total       2580 non-null   object
 1   rating_avg         2580 non-null   float64
 2   finalist           2677 non-null   object
 3   movie_description  2677 non-null   object
 4   cast               2621 non-null   object
 5   language           2651 non-null   object
 6   style              2677 non-null   object
 7   country            2657 non-null   object
 8   company            2677 non-null   object
 9   film_location      890 non-null    object
dtypes: float64(1), object(9)
memory usage: 209.3+ KB